### ISSUE TITLE
要怎样才能有这些日志打出来，我在自己的项目里面没有这些

### ISSUE THREAD

**Issue by Rachelxiao** [netease-im/NIM_Web_Demo#12]
![image](https://user-images.githubusercontent.com/24711330/30316378-9b898ece-97d9-11e7-80fc-ed017494222a.png)

**Comment by www-wwj** [comment]
var nim = NIM.getInstance({
    // debug: true,
});
debug: 是否开启日志, 开发者可以开启日志, 这样 SDK 会将关键操作的信息打印到控制台上, 便于调试

**Comment by Rachelxiao** [comment]
![image](https://user-images.githubusercontent.com/24711330/30317405-9f04ec62-97dc-11e7-8c55-8633b439baf4.png)
![image](https://user-images.githubusercontent.com/24711330/30317428-b06d2f64-97dc-11e7-92d2-fa12441d26cb.png)
写了debug:true也没有效果

**Comment by www-wwj** [comment]
这个是IM的 webrtc目前beat版本

**Comment by Rachelxiao** [comment]
![image](https://user-images.githubusercontent.com/24711330/30319312-26d88a86-97e2-11e7-8948-582364cd75ce.png)
![image](https://user-images.githubusercontent.com/24711330/30319357-3e043b56-97e2-11e7-9752-72397ef3aaf0.png)
![image](https://user-images.githubusercontent.com/24711330/30319496-a0a9c104-97e2-11e7-9a5f-6bfa92160409.png)

我看了demo的debug跟我自己的debug，感觉差不多啊，但是我的就是没有视频出来

**Comment by Rachelxiao** [comment]
![image](https://user-images.githubusercontent.com/24711330/30320828-7630c9b4-97e6-11e7-85eb-6fa9c2d5ea72.png)

![image](https://user-images.githubusercontent.com/24711330/30320838-7eaad5b2-97e6-11e7-948c-56fbb145231c.png)
demo的有node返回，我项目里面没有node返回，是什么原因哦
