### ISSUE TITLE
app 接听视频后，web没有视频显示出来，container里面没有生成video是什么原因？

### ISSUE THREAD

**Issue by Rachelxiao** [netease-im/NIM_Web_Demo#13]
![image](https://user-images.githubusercontent.com/24711330/30367796-dd8dd712-98a1-11e7-9b9f-95472dd9bb1f.png)

![image](https://user-images.githubusercontent.com/24711330/30367802-e9f2d98a-98a1-11e7-9ba9-1d2b80c5b869.png)

![image](https://user-images.githubusercontent.com/24711330/30367815-f32fee7a-98a1-11e7-81b1-411918ebe42a.png)

可以发起视频，可以监听对方接听了，就是没有视频显示出来

joinChannel事件打印出来是这样的：
![image](https://user-images.githubusercontent.com/24711330/30367944-496625e8-98a2-11e7-808d-ce76f830726a.png)

demo返回的是这样的：
![image](https://user-images.githubusercontent.com/24711330/30367980-62812b0e-98a2-11e7-82f6-32ff9d247a9d.png)

我本地返回的少了node节点，是什么原因哦？求解

**Comment by lduoduo** [comment]
WebRTC 的SDK版本多少，v4.2.0之前的版本初始化传入参数container只支持原生dom, 看你第一张图的代码，传入的container是jquery的dom，需要手动转一下的，v4.2.0及以后的版本是支持jquery的dom对象的
