### ISSUE TITLE
Demo  跑起来之后注册不了用户

### ISSUE THREAD

**Issue by tersonly** [netease-im/NIM_Web_Demo#23]
![image](https://user-images.githubusercontent.com/20390658/61845972-e124d580-aed7-11e9-90f5-4fa08c2c168b.png)

**Comment by qq3126986344** [comment]
这是网易官方的IM Web接口，目前这个版本接口停用

**Comment by qq3126986344** [comment]
新版本参考https://github.com/qq3126986344/NIM_Web_Demo

**Comment by tersonly** [comment]
嗯  我去下载的看下

**Comment by tersonly** [comment]
还是这个提示啊，不能注册

**Comment by Claiyre** [comment]
用户注册调用的是云信DEMO业务接口，不支持本地注册呢

如果您没有更改demo里的appkey，可以在[线上环境注册](https://app.yunxin.163.com/webdemo/im/register.html)，然后登录；若您更改了demo的appKey，可以调用云信的服务器接口注册账号，或通过云信用户后台->应用->API调试 注册

**Comment by tersonly** [comment]
已经可以了




------------------ 原始邮件 ------------------
发件人: "马莹莹"<notifications@github.com>; 
发送时间: 2019年8月1日(星期四) 下午5:28
收件人: "netease-im/NIM_Web_Demo"<NIM_Web_Demo@noreply.github.com>; 
抄送: "急灵风慢郎中"<2245918266@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [netease-im/NIM_Web_Demo] Demo  跑起来之后注册不了用户 (#23)




用户注册调用的是云信DEMO业务接口，不支持本地注册呢
 
如果您没有更改demo里的appkey，可以在线上环境注册，然后登录；若您更改了demo的appKey，可以调用云信的服务器接口注册账号，或通过云信用户后台->应用->API调试 注册
 
&mdash;

**Comment by tersonly** [comment]
但是你们发布的那个Demo不用知道为什么不行  你们有个163的地址   我直接看了sdk 调用接口可以了




------------------ 原始邮件 ------------------
发件人: "马莹莹"<notifications@github.com>; 
发送时间: 2019年8月1日(星期四) 下午5:28
收件人: "netease-im/NIM_Web_Demo"<NIM_Web_Demo@noreply.github.com>; 
抄送: "急灵风慢郎中"<2245918266@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [netease-im/NIM_Web_Demo] Demo  跑起来之后注册不了用户 (#23)




用户注册调用的是云信DEMO业务接口，不支持本地注册呢
 
如果您没有更改demo里的appkey，可以在线上环境注册，然后登录；若您更改了demo的appKey，可以调用云信的服务器接口注册账号，或通过云信用户后台->应用->API调试 注册
 
&mdash;
