### ISSUE TITLE
vue-cli3如何使用npm引入

### ISSUE THREAD

**Issue by qm8956** [netease-im/NIM_Web_Demo#26]
通过配置忽略貌似不起作用
`config.module
      .rule('js')
      .exclude.add(resolve('src/components/video_inter/yunxin_sdk'))
      .end();
`
`
 69% building 1439/1441 modules 2 active ..._inter\yunxin_sdk\NIM_Web_SDK_v6.3.0.js
<--- Last few GCs --->

[15960:0000028554ECF3F0]    34566 ms: Scavenge 1278.5 (1437.9) -> 1267.3 (1439.9) MB, 5.0 / 0.0 ms  (average mu = 0.236, current mu = 0.223) allocation failure
[15960:0000028554ECF3F0]    34598 ms: Scavenge 1280.2 (1439.9) -> 1270.0 (1442.4) MB, 5.1 / 0.0 ms  (average mu = 0.236, current mu = 0.223) allocation failure

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0000006D581DC5C1]
    1: StubFrame [pc: 0000006D581CEA81]
Security context: 0x026037a1e6e9 <JSObject>
    2: replace [0000026037A105E9](this=0x012b44c41e89 <Very long string[14894]>,0x012b44c41eb1 <JSRegExp <String[5]: [^\t]>>,0x024c9d789d69 <String[1]:  >)
    3: /* anonymous */(aka /* anonymous */) [0000012B44C41DA1] [E:\portal-workspace\inspect-web-bpm\node_modules\@babel\code-frame\lib\index.js:125] [bytecode=000...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
`
能不能给一个官方的demo呢？希望能发布到npm仓库，也就不用纠结引入的问题了

**Comment by kscript** [comment]
可以将sdk文件放在public目录, 然后在入口文件通过script标签引入, 最后在项目中, 直接使用SDK变量即可

**Comment by qm8956** [comment]
@kscript 当前就是这样解决的，但这样解决不算优雅，而且由于视频通话使用率不高，会给首页加载造成一定负担，希望官方给出npm install模式安装，官方不能用模块形式的原因在哪里？可否告知一下
