### ISSUE TITLE
有一bug，来至notification.js

### ISSUE THREAD

**Issue by windbell2** [netease-im/NIM_Web_Demo#3]
this.mysdk.getUsers(array,function(err,data){
            for (var i = data.length - 1; i >= 0; i--) {
                that.cache.updatePersonlist(data[i])
            }
            //蛋疼的异步处理，必须确保用户消息缓存在本地，再进行UI展示
            that.cache.addMsgs(msg)
            //再次重绘
           	**this.buildSessions()** // => that
            callback() 
        })

**Comment by www-wwj** [comment]
已更正
