### ISSUE TITLE
通过删除接口删除当前会话

### ISSUE THREAD

**Issue by deliveph** [netease-im/NIM_Web_Demo#8]
怎么把会话列表的当前会话也移出出去
![m r 8 rodv aw frjg2t8](https://user-images.githubusercontent.com/15628862/27522484-fb2769dc-5a58-11e7-8e81-a27029ceb5e1.png)

**Comment by www-wwj** [comment]
http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/Web%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90?#删除本地会话
http://dev.netease.im/docs/product/IM%E5%8D%B3%E6%97%B6%E9%80%9A%E8%AE%AF/SDK%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90/Web%E5%BC%80%E5%8F%91%E9%9B%86%E6%88%90?#删除服务器上的会话
调用者2个接口

**Comment by deliveph** [comment]
![_23zbr16qcobu 4ri wk78u](https://user-images.githubusercontent.com/15628862/27522800-43295ca2-5a5b-11e7-84e3-6ac9c6a75397.png)
并且我试了这个两个接口都还是会出现

**Comment by www-wwj** [comment]
实测可以 你要做的就是处理这3件事1.上层删除缓存内存数据（处理按钮点击后的UI显示） 2.删除数据库会话数据 deleteLocalSession3.删除服务器会话数据deleteSession 刷新后也不会出现

**Comment by deliveph** [comment]
缓存数据指的是本地会话吗

**Comment by www-wwj** [comment]
上层做的缓存数据用于驱动UI展示，类似demo的cache层

**Comment by deliveph** [comment]
好的，多谢

**Comment by deliveph** [comment]
我试了，可以通过deleteLocalSession 和  deleteSession 来清除掉，但是要刷新页面之后，会话列表才会没有删除的那个，不然还是会有

**Comment by www-wwj** [comment]
你本地UI没有处理呀
